---
title: Indivisible MN03
timezone: UTC
collections:
  successes:
    title: Media Attention
    output: true
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    is featured: false
    main-image:
    call-script-text:
    event-start-date:
    event-end-date:
    Location:
    RSVP-link:
    layout: post
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: ''
    type: representatives
  values:
    phone-numbers:
      office-name: "(000) 000-0000"
    website:
- scope:
    path: ''
    type: successes
  values:
    is featured: false
    main-image:
    layout: media-item
- scope:
    path: ''
    type: calendar
  values:
    embed-code:
- scope:
    path: ''
    type: becomeAMember
  values:
    main-image:
    mailchimp-form-embed: '<!-- Begin MailChimp Signup Form --><link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css"><style type="text/css">#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }/* Add your own MailChimp form style overrides in your site stylesheet or in this style block. We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */</style><div id="mc_embed_signup"><form action="https://whereiserikpaulsen.us15.list-manage.com/subscribe/post?u=821493f0a86a59c330ced5e6f&amp;id=55ee14156e" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate><div id="mc_embed_signup_scroll"><h2>Subscribe to our newsletter</h2><div class="indicates-required"><span class="asterisk">*</span> indicates required</div><div class="mc-field-group"><label for="mce-EMAIL">Email Address  <span class="asterisk">*</span></label><input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL"></div><div class="mc-field-group"><label for="mce-FNAME">First Name </label><input type="text" value="" name="FNAME" class="" id="mce-FNAME"></div><div class="mc-field-group"><label for="mce-LNAME">Last Name </label><input type="text" value="" name="LNAME" class="" id="mce-LNAME"></div><div id="mce-responses" class="clear"><div class="response" id="mce-error-response" style="display:none"></div><div class="response" id="mce-success-response" style="display:none"></div></div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups--><div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_821493f0a86a59c330ced5e6f_55ee14156e" tabindex="-1" value=""></div><div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div></div></form></div><script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script><!--End mc_embed_signupâ€”>'
- scope:
    path: ''
    type: townhall
  values:
    main-image:
subtitle:
email: indivisiblemn03@gmail.com
baseurl:
url:
twitter_username: "/IndivisibleMN03"
facebook_username: IndivisibleMN03
background-image: uploads/banner_indivisible_mn03_wide.png
member-count: 1600
footer-title: Spread the word. Help build a movement.
markdown: kramdown
gems:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
paginate: 10
paginate_path: "/blog/page:num/"
exclude:
- Gemfile
- Gemfile.lock
google_analytics:
theme: jekyll-theme-cayman
